import numpy as np
a=np.array([1,2,3])
b=np.array([(1,2,3),(4,5,6)])
c=np.array([(1,2,3),(4,5,6),(6,7,8)])
d=np.array([(2,1,1),(3,2,2),(5,6,7)])

print("a ",a)
print("b",b)
print("dimension",a.ndim)
print("dimension",b.ndim)
print(a.itemsize)
print(b.itemsize)
print(a.dtype)
print(b.dtype)
print(a.shape)
print(b.shape)
print(b.reshape(3,2))
print(np.linspace(1,3,))
x=np.vstack((c,d))
y=np.hstack((c,d))
print(x)
print(y)
